version: '3.8'
services:
  angularapp:
    build: ./task-tracker-client
    ports:
      - 4200:4200
    restart: always

  expressapp:
    build: ./task-tracker-server
    ports:
      - 3000:3000
    restart: always
      
  mongodb:
    image: mongo
    ports:
      - 27018:27017
    


